### ISSUE TITLE
Optie chatfunction

### ISSUE THREAD

**Issue by Timmhart** [MichaelChorak/matching-app#3]
Dag team!

Samen met een student assistent zijn we uitgekomen op een idee voor de chat. 
Ieder persoon die een bepaald gerecht liked wordt geplaatst in de room die gekoppeld is aan het gerecht. Het is mogelijk voor mij om rooms aan te maken met socket.io en ik kan met de volgende code ervoor zorgen dat de berichten alleen in deze chat te zien zijn

`socket.to("game").emit("nice game", "let's play a game");`

Het is dus dan zo dat er meer dan 2 personen in een bepaalde room komen.
Wat vinden jullie hier van?

**Comment by MichaelChorak** [comment]
Lijkt mij voor nu een goede oplossing en zeker in deze context (beperkte tijd).
Alleen moeten we een fallback hebben voor meerdere gelikte gerechten, of is het zo dat je 'liked' direct in de chat komt? of kan je er op een later moment in terug komen?

**Comment by Timmhart** [comment]
Goed punt! Daar heb je zeker gelijk in. Ik ga me eerst dan even focussen om de personen in de room te krijgen en vanaf daar kijken naar hoe ik ze er eventueel uit kan krijgen. How about that?

**Comment by soofg** [comment]
Goede optie dit!!

**Comment by Hoa0** [comment]
Goed alternatief, denk dat het voor de gebruiker ook leuk is om in contact te komen met meerdere mensen.

**Comment by woutarb** [comment]
Works at this time, closed issue.
